#!/usr/bin/python

import os

def is_numeric(string):
	try:
		float(string)
		return True
	except:
		return False

time_dir = os.path.abspath('new_Aniso')
config_dir = os.path.abspath('cb_configs')

dirs = [os.path.join(time_dir, dir) \
	for dir in os.listdir(time_dir) if is_numeric(dir)]

for dir in dirs:
	os.chdir(dir)
	output_dir = os.path.join(config_dir, dir.split('/')[-1])
	if not os.path.exists(output_dir):
		os.makedirs(output_dir)
	command_template = 'trjconv_d -f traj.trr -o %(d)s/%(t)s.pdb -b %(t)s -e %(t)s'
	for time in range(5000, 11000, 1000):
		if not os.path.exists(os.path.join(config_dir, str(time) + '.pdb')):
			os.system('echo 0 |' + command_template % {'d': output_dir, 't': time})