#!/usr/bin/env python

import raman
from os import putenv
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import re

def find_time(string):
	match = [item for item in string.split('/') if re.match(r'[0-9]+ps$', item)][0]
	if match:
		return match
	else:
		return string

# Make script end in interactive mode
putenv('PYTHONINSPECT', 't')

configs = [raman.Configuration.from_log_file(f) for f in sys.argv[1:] if f.endswith('.log')]
